paginate: 10
paginate_path: "page:num"
plugins:
    - jekyll-paginate
    - jekyll-sitemap

markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    syntax_highlighter: rouge
    auto_ids: true

syntax_theme: github

comments: livere
domain: https://qii404.me

name: qii404|齐士博博客
author:
    name: 齐士博
description: 一个叫齐士博的人写的技术博客，网名叫小齐炖博士，也有叫qii404的，写字的，码农一个，web开发
