paginate: 10
paginate_path: "page:num"
gems:
    - jekyll-paginate
    - jekyll-sitemap

markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    syntax_highlighter: rouge
    auto_ids: true

syntax_theme: github

comments: livere

name: qii404|齐士博博客
